# Generated by Django 4.0.4 on 2022-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_products_is_trandy'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_arrived',
            field=models.BooleanField(default=False),
        ),
    ]
