# Generated by Django 4.0.4 on 2022-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_productcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClotheTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Clothe type category',
                'verbose_name_plural': 'Clothe type categories',
            },
        ),
    ]
